[package]
name = "rocket_example"
version = "0.1.0"
authors = ["Gambhiro <gambhiro.bhikkhu.85@gmail.com>"]
edition = "2018"

[dependencies]
glium = "0.17.0"
notify = "3.0"

rocket_client = "0.1"
rocket_sync = "0.1"
